name: nc-fastapi
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - ffmpeg=4.2.2
  - freetype=2.11.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - lame=3.100
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libunistring=0.9.10
  - libvpx=1.7.0
  - ncurses=6.3
  - nettle=3.7.3
  - openh264=2.1.1
  - openssl=1.1.1s
  - pip=21.2.4
  - python=3.9.12
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.3
  - tk=8.6.11
  - tzdata=2022a
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - aiosqlite==0.17.0
    - anyio==3.6.1
    - asgiref==3.5.2
    - asyncpg==0.25.0
    - click==8.1.3
    - databases==0.5.5
    - fastapi==0.78.0
    - greenlet==1.1.2
    - gunicorn==20.1.0
    - h11==0.13.0
    - idna==3.3
    - jinja2==3.1.2
    - markupsafe==2.1.1
    - psycopg2==2.9.3
    - pydantic==1.9.1
    - pydub==0.25.1
    - sniffio==1.2.0
    - sqlalchemy==1.4.36
    - starlette==0.19.1
    - typing-extensions==4.2.0
    - uvicorn==0.17.6
    - websockets==10.3
